apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-app
  namespace: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
    spec:
      containers:
        - name: root
          image: dashalovenorth/root-service:latest
          envFrom:
            - configMapRef:
                name: root-config
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"